create table public.recommendation_queue (
  id uuid primary key default gen_random_uuid(),
  actor_type text not null check (actor_type in ('user', 'team')),
  actor_id uuid not null,
  target_type text not null check (target_type in ('user', 'team')),
  target_id uuid not null,
  score real not null default 0,
  sequence bigint generated always as identity,
  created_by_user_id uuid not null
    references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint recommendation_queue_supported_direction_check check (
    (actor_type = 'user' and target_type in ('user', 'team'))
    or (actor_type = 'team' and target_type = 'user')
  ),
  constraint recommendation_queue_distinct_user_check check (
    actor_type <> 'user'
    or target_type <> 'user'
    or actor_id <> target_id
  ),
  constraint recommendation_queue_user_actor_owner_check check (
    actor_type <> 'user' or actor_id = created_by_user_id
  )
);

comment on table public.recommendation_queue is
  'Precomputed, disposable candidate queue per actor. Regenerated by a backend job; rows are removed once a decision exists in swipes. Not a source of truth — safe to truncate and recompute.';

-- one active queue entry per (actor, target); upsert on refill to update score
create unique index recommendation_queue_actor_target_unique_idx
  on public.recommendation_queue (actor_type, actor_id, target_type, target_id);

-- the "pop next N" read path: this is the index that matters
create index recommendation_queue_actor_order_idx
  on public.recommendation_queue (actor_type, actor_id, score desc, sequence asc);

-- auto-dequeue: once a swipe decision exists, it has no business staying in the queue
create function public.dequeue_recommendation_on_swipe()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  delete from public.recommendation_queue
  where actor_type = new.actor_type
    and actor_id = new.actor_id
    and target_type = new.target_type
    and target_id = new.target_id;
  return new;
end;
$$;

create trigger swipes_dequeue_recommendation
after insert on public.swipes
for each row execute function public.dequeue_recommendation_on_swipe();

revoke execute on function public.dequeue_recommendation_on_swipe() from public, anon, authenticated;

alter table public.recommendation_queue enable row level security;
revoke all on table public.recommendation_queue from anon, authenticated;

-- clients only ever read their own queue; writes come from a trusted backend/service role
grant select on table public.recommendation_queue to authenticated;

create policy recommendation_queue_read_own
on public.recommendation_queue
for select
to authenticated
using (created_by_user_id = (select auth.uid()));
